"""DOCX document generator for exporting study materials."""

import io
import os
from typing import Optional
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def create_study_document(content: str, mode: str) -> bytes:
    """Generate a DOCX file from study material content.
    
    Args:
        content: The text content to include in the document.
        mode: The generation mode ('summary' or 'reviewer').
        
    Returns:
        DOCX file as bytes.
    """
    document = Document()
    
    # Add title based on mode
    title = "NoteTakrr Study Guide" if mode == "summary" else "NoteTakrr Review Questions"
    document.add_heading(title, 0)
    
    # Add disclaimer
    disclaimer = document.add_paragraph("Generated by NoteTakrr — AI-generated content. Always verify accuracy against original sources.")
    disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    disclaimer.runs[0].italic = True
    disclaimer.runs[0].font.size = Pt(9)
    
    document.add_paragraph() # Add a little spacing
    
    # Basic Markdown parsing
    lines = content.split('\n')
    in_code_block = False
    
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
            
        if stripped.startswith('```'):
            in_code_block = not in_code_block
            continue
            
        if in_code_block:
            p = document.add_paragraph(stripped)
            p.runs[0].font.name = 'Courier New'
            continue
            
        # Headings
        if stripped.startswith('# '):
            document.add_heading(stripped[2:].replace('**', ''), level=1)
        elif stripped.startswith('## '):
            document.add_heading(stripped[3:].replace('**', ''), level=2)
        elif stripped.startswith('### '):
            document.add_heading(stripped[4:].replace('**', ''), level=3)
        # Lists
        elif stripped.startswith('- ') or stripped.startswith('* '):
            document.add_paragraph(stripped[2:].replace('**', ''), style='List Bullet')
        # Bold Q&A pairs parsing (e.g. **Q1:**)
        elif stripped.startswith('**') and '**' in stripped[2:]:
            p = document.add_paragraph()
            parts = stripped.split('**')
            for i, part in enumerate(parts):
                if not part: continue
                run = p.add_run(part)
                if i % 2 == 1: # The text inside ** **
                    run.bold = True
        else:
            # Regular paragraph, strip bold markers for simplicity
            document.add_paragraph(stripped.replace('**', ''))
            
    # Save to BytesIO
    file_stream = io.BytesIO()
    document.save(file_stream)
    return file_stream.getvalue()


def save_docx_to_file(docx_bytes: bytes, filename: str) -> str:
    """Save DOCX bytes to the outputs directory.
    
    Args:
        docx_bytes: The DOCX file content as bytes.
        filename: Name for the output file.
        
    Returns:
        Path to the saved file.
    """
    # Ensure outputs directory exists (backend/outputs)
    current_dir = os.path.dirname(os.path.abspath(__file__))
    outputs_dir = os.path.join(os.path.dirname(os.path.dirname(current_dir)), "outputs")
    os.makedirs(outputs_dir, exist_ok=True)
    
    file_path = os.path.join(outputs_dir, filename)
    with open(file_path, "wb") as f:
        f.write(docx_bytes)
        
    return file_path
